name: br
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5673638652078807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#20130b'
    - '#448ac8'
    - '#7e4f00'
    - '#fedcc0'
    - '#fcaa00'
  brandStrength: 0.4184907702729106
  lightness: 0.3038661547470838
  saturation: 0.31933895871043205
  rhythmicContrast: 0.08444853289984167
purpose: []
