name: br
favicon: null
layout_spectrum: 0.13813989236950874
typography_spectrum: 0.5673638652078807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.4184907702729106
  lightness: 0.3038661547470838
  saturation: 0.31933895871043205
  rhythmicContrast: 0.08444853289984167
purpose: []
